apiVersion: v1
kind: Pod
metadata:
  name: rss-site
  labels:
    app: nginx
    rel: stable
spec:
  containers:
    - name: front-end
      image: nginx:alpine
      ports:
        - containerPort: 80
